<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UsingGenerator.Abstractions\UsingGenerator.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\UsingGenerator.Generator\UsingGenerator.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\UsingGenerator.Sample.Library\UsingGenerator.Sample.Library.csproj" />
  </ItemGroup>

</Project>
